apiVersion: v2
name: sonarr-operator
description: >-
  A Kubernetes operator for managing Sonarr instances and their configuration
  via Custom Resources
type: application
version: 0.2.0
appVersion: 0.1.0
kubeVersion: '>=1.28.0-0'
home: https://github.com/devopsarr/k8s-operator-sonarr
sources:
  - https://github.com/devopsarr/k8s-operator-sonarr
maintainers:
  - name: DevOpsArr
    url: https://github.com/devopsarr
keywords:
  - sonarr
  - operator
  - kubernetes
  - kube-rs
  - media
  - arr
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: GPL-3.0
  artifacthub.io/operator: 'true'
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/prerelease: 'true'
